const LOGIN_ROUTE = '/login';

const MAIN_ROUTE = '/';

const USERS_ROUTE = '/users';
const USERS_CREATE_ROUTE = USERS_ROUTE + '/create';
const USERS_EDIT_ROUTE = USERS_ROUTE + '/edit';

const ROLES_ROUTE = '/roles';
const ROLES_CREATE_ROUTE = ROLES_ROUTE + '/create';
const ROLES_EDIT_ROUTE = ROLES_ROUTE + '/edit';

const LICENSES_ROUTE = '/licenses';
const LICENSES_CREATE_ROUTE = LICENSES_ROUTE + '/create';
const LICENSES_EDIT_ROUTE = LICENSES_ROUTE + '/edit';

const REQUIREMENTS_ROUTE = '/requirements';
const REQUIREMENTS_CREATE_ROUTE = REQUIREMENTS_ROUTE + '/create';
const REQUIREMENTS_EDIT_ROUTE = REQUIREMENTS_ROUTE + '/edit';

const JOB_OPENINGS_ROUTE = '/job-openings';
const JOB_OPENINGS_CREATE_ROUTE = JOB_OPENINGS_ROUTE + '/create';
const JOB_OPENINGS_EDIT_ROUTE = JOB_OPENINGS_ROUTE + '/edit';

const NEWS_ROUTE = '/news';
const NEWS_CREATE_ROUTE = NEWS_ROUTE + '/create';
const NEWS_EDIT_ROUTE = NEWS_ROUTE + '/edit';

const PROJECTS_ROUTE = '/projects';

const EMPLOYEES_ROUTE = '/employees';
const EMPLOYEES_CREATE_ROUTE = EMPLOYEES_ROUTE + '/create';
const EMPLOYEES_EDIT_ROUTE = EMPLOYEES_ROUTE + '/edit';

const CONTACTS_BRANCHES_ROUTE = '/contacts-branches';
const CONTACTS_BRANCHES_CREATE_ROUTE = CONTACTS_BRANCHES_ROUTE + '/create';
const CONTACTS_BRANCHES_EDIT_ROUTE = CONTACTS_BRANCHES_ROUTE + '/edit';
// const _ROUTE = '/';

export const ROUTES = {
    MAIN_ROUTE,
    LOGIN_ROUTE,
    ROLES_ROUTE,
    ROLES_CREATE_ROUTE,
    ROLES_EDIT_ROUTE,
    USERS_ROUTE,
    USERS_CREATE_ROUTE,
    USERS_EDIT_ROUTE,
    LICENSES_ROUTE,
    LICENSES_CREATE_ROUTE,
    LICENSES_EDIT_ROUTE,
    REQUIREMENTS_ROUTE,
    REQUIREMENTS_CREATE_ROUTE,
    REQUIREMENTS_EDIT_ROUTE,
    JOB_OPENINGS_ROUTE,
    JOB_OPENINGS_CREATE_ROUTE,
    JOB_OPENINGS_EDIT_ROUTE,
    NEWS_ROUTE,
    NEWS_CREATE_ROUTE,
    NEWS_EDIT_ROUTE,
    EMPLOYEES_ROUTE,
    EMPLOYEES_CREATE_ROUTE,
    EMPLOYEES_EDIT_ROUTE,
    CONTACTS_BRANCHES_ROUTE,
    CONTACTS_BRANCHES_CREATE_ROUTE,
    CONTACTS_BRANCHES_EDIT_ROUTE,
    PROJECTS_ROUTE,
};